### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by moonlight200**
- updated the dependencies
- updated target SDK version
- updated Android plugin version
- updated Gradle version
- ~added Android Studio project files~

### CODE REVIEW

**Comment by moonlight200** [comment]
As soon as this PR is accepted I can create a PR for the [rv-adapter-states](https://github.com/rockerhieu/rv-adapter-states) as it has this library as a dependency.

**Comment by rockerhieu** [comment]
Android Studio files are unnecessary to track, please remove them.

**Comment by moonlight200** [comment]
I thought they might help others to contribute, but I can remove them, sure :)

**Comment by rockerhieu** [comment]
looking good, merged :+1:

**Comment by rockerhieu** [comment]
Some how `1.1` is screwed up on mavenCentral() and jcenter(). I've pushed it out again under version `1.2`. Hope all's good,

**Comment by rockerhieu** [comment]
After `1.2` is live I will merge https://github.com/rockerhieu/rv-adapter-states/pull/6/.

**Pull request merged**
